# Generated by Django 6.0.6 on 2026-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(choices=[('Amman', 'عمان'), ('Irbid', 'إربد'), ('Zarqa', 'الزرقاء'), ('Mafraq', 'المفرق'), ('Jerash', 'جرش'), ('Ajloun', 'عجلون'), ('Salt', 'السلط (البلقاء)'), ('Madaba', 'مأدبا'), ('Karak', 'الكرك'), ('Tafilah', 'الطفيلة'), ("Ma'an", 'معان'), ('Aqaba', 'العقبة')], default='Amman', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(choices=[('Amman', 'عمان'), ('Irbid', 'إربد'), ('Zarqa', 'الزرقاء'), ('Mafraq', 'المفرق'), ('Jerash', 'جرش'), ('Ajloun', 'عجلون'), ('Salt', 'السلط (البلقاء)'), ('Madaba', 'مأدبا'), ('Karak', 'الكرك'), ('Tafilah', 'الطفيلة'), ("Ma'an", 'معان'), ('Aqaba', 'العقبة')], default='Amman', max_length=50),
        ),
    ]
